# Generated by Django 5.1.1 on 2024-09-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField()),
                ('engine_temp', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('alert_type', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('non_critical', 'Non-Critical')], default='non_critical', max_length=20)),
                ('impact', models.IntegerField(default=0)),
            ],
        ),
    ]
