# Generated by Django 5.1.1 on 2024-09-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alt_mobility_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_provider_issuer', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('renewal_status', models.BooleanField(blank=True, null=True)),
                ('time_due', models.IntegerField(blank=True, null=True)),
                ('policy_number', models.TextField(blank=True, null=True)),
                ('offline_days', models.IntegerField(blank=True, null=True)),
                ('idle_days', models.IntegerField(blank=True, null=True)),
                ('min_cell_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_soc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('days_since', models.IntegerField(blank=True, null=True)),
                ('alert_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alt_mobility_api_app.alert')),
            ],
            options={
                'db_table': 'additional_alerts',
                'managed': True,
            },
        ),
    ]
